import { BGM, SFX } from '../../../data/audioData.js';
import { BG } from '../backgrounds.js';

export const pathC = {
  // ===================================================================
  // PATH C — THE WRONG PLACE (Psychological/Surreal) - MASSIVELY EXPANDED
  // ===================================================================
  C_followLaughter: {
    speaker: 'Narrator',
    text: "You follow the laughter to the Children's Ward. The hallway is unnervingly clean, the walls painted with cheerful, faded murals of cartoon animals.",
    background: BG.childrens_ward,
    bgm: BGM.softHaunt,
    choices: [{ text: '...', next: 'C_followLaughter_b' }],
  },
  C_followLaughter_b: {
    speaker: 'Narrator',
    text: "It's utterly silent now. Doors lead to a Playroom, a Quiet Room, and a Classroom. You feel a profound sense of wrongness here.",
    background: BG.childrens_ward,
    revisitText:
      "You are back in the eerily clean hallway of the Children's Ward. Something is deeply wrong here.",
    choices: [
      { text: 'Enter the Playroom.', next: 'C_playroom' },
      { text: 'Enter the Quiet Room.', next: 'C_quietroom' },
      { text: 'Enter the Classroom.', next: 'C_classroom' },
      { text: 'Examine the hallway more closely.', next: 'C_hallwayAnomaly' },
      { text: 'Go back to the main hallway.', next: 'hallwayEntry' },
    ],
  },
  C_hallwayAnomaly: {
    speaker: 'Narrator',
    text: 'You look closer at the murals. The cartoon rabbit has eyes that are too human, and they seem to follow you. The painted sun is weeping black tears.',
    background: BG.childrens_ward,
    choices: [{ text: '...', next: 'C_hallwayAnomaly_b' }],
  },
  C_hallwayAnomaly_b: {
    speaker: 'Narrator',
    text: 'One of the floor tiles is perfectly clean, while the others are yellowed with age. You feel a creeping dread. This place is a lie.',
    background: BG.childrens_ward,
    effects: { stats: { sanity: -5 } },
    choices: [
      { text: "I need to find what's real.", next: 'C_followLaughter' },
    ],
  },
  C_playroom: {
    speaker: 'Narrator',
    text: 'The playroom is filled with vintage toys, all neatly arranged. Rocking horses, building blocks, dolls with vacant glass eyes.',
    background: BG.childrens_ward,
    revisitText: 'The playroom is just as unsettling as before.',
    choices: [{ text: '...', next: 'C_playroom_b' }],
  },
  C_playroom_b: {
    speaker: 'Narrator',
    text: 'In the center of the room is a small table with a single, pristine, red apple on it. A music box on a shelf sits closed. One of the dolls is weeping bloody tears.',
    background: BG.childrens_ward,
    choices: [
      { text: 'Take the Perfect Apple (Anomaly 1/5).', next: 'C_takeApple' },
      {
        text: 'Wipe the tears from the doll (Anomaly 2/5).',
        next: 'C_wipeTears',
      },
      { text: 'Open the music box.', next: 'C_musicBox' },
      { text: 'Leave.', next: 'C_followLaughter' },
    ],
  },
  C_takeApple: {
    speaker: 'Narrator',
    text: 'You pick up the apple. It is an anomaly, a thing of perfect order in a world of decay. The room flickers, and you see rusted, broken toys and bloodstains.',
    background: BG.childrens_ward,
    visualEffect: 'glitch',
    sfx: SFX.glitch,
    effects: {
      inventory: { add: 'perfect_apple' },
      flags: { set: 'C_anomaly1' },
    },
    choices: [{ text: 'One down.', next: 'C_playroom_after' }],
  },
  C_wipeTears: {
    speaker: 'Narrator',
    text: "You wipe the blood from the doll's cheek. It is warm and sticky. The doll's head slowly turns to look at you, its eyes filled with sorrow. This act is an anomaly here.",
    background: BG.childrens_ward,
    visualEffect: 'glitch',
    sfx: SFX.glitch,
    effects: { stats: { morality: 5 }, flags: { set: 'C_anomaly2' } },
    choices: [{ text: 'Two.', next: 'C_playroom_after' }],
  },
  C_musicBox: {
    speaker: 'Narrator',
    text: 'You open the music box. Instead of a melody, it plays a discordant screech. A tiny, rotten human finger pops up and spins. You slam it shut.',
    background: BG.childrens_ward,
    sfx: SFX.musicBox,
    jumpscare: { type: 'sprite', character: 'figure', sfx: SFX.jumpscare },
    effects: { stats: { sanity: -10 } },
    choices: [{ text: 'Horrible.', next: 'C_playroom_after' }],
  },
  C_playroom_after: {
    speaker: 'Lily',
    text: "'Don't touch my things,' a voice whispers in your ear. You spin around, but no one is there.",
    background: BG.childrens_ward,
    sfx: SFX.shadow_whisper,
    effects: { stats: { sanity: -5 } },
    choices: [{ text: 'Leave.', next: 'C_checkAnomalies' }],
  },
  C_quietroom: {
    speaker: 'Narrator',
    text: 'This was a room for calming agitated children. The walls are padded. In the corner is a single, child-sized bed with a perfectly made blanket.',
    background: BG.childrens_ward,
    revisitText: 'The padded quiet room. The silence is unnerving.',
    choices: [{ text: '...', next: 'C_quietroom_b' }],
  },
  C_quietroom_b: {
    speaker: 'Narrator',
    text: 'A book lies on the pillow. The pages are completely, unnaturally blank.',
    background: BG.childrens_ward,
    choices: [
      { text: 'Take the Blank Book (Anomaly 3/5).', next: 'C_takeBook' },
      { text: 'Look under the bed.', next: 'C_underBed' },
      { text: 'Leave.', next: 'C_followLaughter' },
    ],
  },
  C_takeBook: {
    speaker: 'Narrator',
    text: 'You take the book. Its unnatural emptiness feels wrong. Another anomaly. The padded walls briefly appear torn and stained before the illusion reasserts itself.',
    background: BG.childrens_ward,
    visualEffect: 'glitch',
    sfx: SFX.glitch,
    effects: { inventory: { add: 'blank_book' }, flags: { set: 'C_anomaly3' } },
    choices: [{ text: 'Three.', next: 'C_quietroom_after' }],
  },
  C_quietroom_after: {
    speaker: 'Narrator',
    text: 'The silence in here is now deafening. What now?',
    background: BG.childrens_ward,
    choices: [
      { text: 'Look under the bed.', next: 'C_underBed' },
      { text: 'Leave.', next: 'C_checkAnomalies' },
    ],
  },
  C_underBed: {
    speaker: 'Narrator',
    text: 'You kneel and look under the bed. Two small, pale hands dart out and grab your face, pulling you towards the darkness. You scramble back. Nothing is there.',
    background: BG.childrens_ward,
    jumpscare: {
      type: 'image',
      image: 'https://i.imgur.com/5zL8QPv.png',
      sfx: 'ghost_scream',
    },
    effects: { stats: { sanity: -15, stamina: -10 } },
    choices: [{ text: 'Never again.', next: 'C_quietroom_after' }],
  },
  C_classroom: {
    speaker: 'Narrator',
    text: 'An old classroom. On the blackboard, someone has written "I AM NOT REAL" over and over. A toy clock on the desk is ticking perfectly.',
    background: BG.childrens_ward,
    revisitText: 'The classroom, with its endless scrawl on the blackboard.',
    ambientSfx: [{ triggerWord: 'ticking', sfx: SFX.clock_tick_reverse }],
    choices: [{ text: '...', next: 'C_classroom_b' }],
  },
  C_classroom_b: {
    speaker: 'Narrator',
    text: 'On a medical tray is a single, gleaming scalpel, untouched by rust or time.',
    background: BG.childrens_ward,
    choices: [
      { text: 'Take the Toy Clock (Anomaly 4/5).', next: 'C_takeClock' },
      { text: 'Take the Clean Scalpel (Anomaly 5/5).', next: 'C_takeScalpel' },
      { text: 'Look inside the desk.', next: 'C_openDesk' },
      { text: 'Leave.', next: 'C_followLaughter' },
    ],
  },
  C_takeClock: {
    speaker: 'Narrator',
    text: "You take the clock. In a place where time feels broken, its perfect function is a deep violation. An anomaly. The children's drawings on the wall morph for a second.",
    background: BG.childrens_ward,
    visualEffect: 'glitch',
    sfx: SFX.glitch,
    effects: {
      inventory: { add: 'working_clock' },
      flags: { set: 'C_anomaly4' },
    },
    choices: [{ text: 'Four.', next: 'C_classroom_after' }],
  },
  C_takeScalpel: {
    speaker: 'Narrator',
    text: 'You take the scalpel. It is surgically clean. Impossible in this filthy place. Anomaly five. The words on the blackboard writhe like worms before settling.',
    background: BG.childrens_ward,
    visualEffect: 'glitch',
    sfx: SFX.glitch,
    effects: {
      inventory: { add: 'clean_scalpel' },
      flags: { set: 'C_anomaly5' },
    },
    choices: [{ text: 'Five.', next: 'C_classroom_after' }],
  },
  C_classroom_after: {
    speaker: 'Narrator',
    text: 'The classroom feels wrong. You feel watched.',
    background: BG.childrens_ward,
    choices: [
      { text: 'Look inside the desk.', next: 'C_openDesk' },
      { text: 'Leave.', next: 'C_checkAnomalies' },
    ],
  },
  C_openDesk: {
    speaker: 'Narrator',
    text: "You open the teacher's desk. It is filled to the brim with human teeth. Hundreds of them. A small, child-like skull sits in the middle like a macabre jewel.",
    background: BG.childrens_ward,
    effects: { stats: { sanity: -10 } },
    choices: [{ text: 'Slam it shut.', next: 'C_classroom_after' }],
  },
  C_checkAnomalies: {
    speaker: 'Narrator',
    text: 'You feel a shift in the air, a weakening of the illusion.',
    background: BG.childrens_ward,
    choices: [
      {
        text: 'Continue.',
        next: 'C_lilyChaseStart',
        requires: {
          flags: [
            'C_anomaly1',
            'C_anomaly2',
            'C_anomaly3',
            'C_anomaly4',
            'C_anomaly5',
          ],
        },
      },
      { text: 'Go back to the ward.', next: 'C_followLaughter' },
    ],
  },
  C_lilyChaseStart: {
    speaker: 'Lily',
    npc: 'ghost',
    text: "'You broke my pretty room,' she whispers, her voice suddenly dropping to a low, guttural snarl full of cold rage. 'You broke all the rules. Now you have to play a new game... a FOREVER game.'",
    background: BG.childrens_ward,
    textEffects: [{ word: 'FOREVER', effect: 'anger' }],
    bgm: BGM.descent,
    sfx: SFX.reality_warp,
    choices: [{ text: '...', next: 'C_lilyChaseStart_b' }],
  },
  C_lilyChaseStart_b: {
    speaker: 'Lily',
    npc: 'ghost',
    text: "'It's called HIDE.' You spin around. The hallway is twisting, warping, the murals on the wall screaming. She is gliding towards you, her blank face a mask of fury.",
    background: BG.childrens_ward,
    choices: [{ text: 'RUN!', next: 'C_chase_1' }],
  },
  C_chase_1: {
    speaker: 'Narrator',
    text: 'You run as the clean hallway around you decays in real time. Doors slam open and shut. The floor ahead of you becomes the ceiling. You hear her laughter everywhere.',
    background: BG.childrens_ward,
    choices: [
      {
        text: 'Leap across the chasm that just opened in the floor!',
        next: 'C_chase_Leap',
      },
      {
        text: 'Duck through a doorway that just appeared!',
        next: 'C_chase_Door',
      },
    ],
    timer: 5,
    defaultChoiceIndex: 1,
  },
  C_chase_Leap: {
    speaker: 'Narrator',
    text: 'You leap across the impossible gap, landing hard. But the perspective shifts again, and you find yourself running back the way you came, directly towards her.',
    background: BG.childrens_ward,
    effects: { stats: { stamina: -20, health: -10 } },
    choices: [{ text: "It's a trap!", next: 'C_lilyCatch' }],
  },
  C_chase_Door: {
    speaker: 'Narrator',
    text: "You dive through a shimmering doorway. You're in a long, dark corridor that seems to stretch into infinity. At the far end, you see a single, impossibly clean mirror.",
    background: BG.childrens_ward,
    choices: [{ text: 'Run for the mirror!', next: 'C_mirror' }],
  },
  C_lilyCatch: {
    speaker: 'Lily',
    isDeath: true,
    background: BG.childrens_ward,
    text: "'You can't run from my world,' she whispers as her icy hands phase through your chest and grip your heart. 'Now you can be one of my pretty things. Forever.'",
  },
  C_mirror: {
    speaker: 'Narrator',
    text: 'You sprint towards the mirror. Her chilling laughter is right behind you. As you reach it, your reflection holds out its hand. Do you take it?',
    background: BG.childrens_ward,
    choices: [
      { text: "Take your reflection's hand.", next: 'C_mirrorRealm' },
      { text: 'Smash the mirror.', next: 'C_smashMirrorFail' },
    ],
  },
  C_smashMirrorFail: {
    speaker: 'Narrator',
    text: "You try to smash the mirror, but your fist passes through it as if it's water. Lily's ghost emerges from the glass and embraces you in a soul-freezing hug.",
    background: BG.childrens_ward,
    choices: [{ text: 'Trapped.', next: 'C_lilyCatch' }],
  },
  C_mirrorRealm: {
    speaker: 'Narrator',
    text: 'You are pulled through the mirror into a twisted, negative version of the ward. The colors are inverted. Gravity feels wrong.',
    background: BG.mirror_realm,
    choices: [{ text: '...', next: 'C_mirrorRealm_b' }],
  },
  C_mirrorRealm_b: {
    speaker: 'Narrator',
    text: 'Your reflection stands before you, its face a featureless mask of rage. In the corner, you see the real Lily, a small, crying, translucent child. You have to reach her.',
    background: BG.mirror_realm,
    choices: [
      { text: 'Confront the angry reflection.', next: 'C_confrontReflection' },
      { text: 'Go to the crying child.', next: 'C_comfortLily' },
    ],
  },
  C_confrontReflection: {
    speaker: 'Narrator',
    text: 'You face the reflection. It lets out a deafening psychic scream, and your mind is torn apart by pure, undiluted rage.',
    background: BG.mirror_realm,
    effects: { stats: { sanity: -100 } },
    choices: [{ text: 'Your mind breaks.', next: 'C_lilyCatch' }],
  },
  C_comfortLily: {
    speaker: 'Narrator',
    text: 'You ignore the monster and go to the crying child. You reach out, not with aggression, but with pity. "It\'s okay," you whisper.',
    background: BG.mirror_realm,
    effects: { stats: { morality: 10 } },
    choices: [{ text: '...', next: 'C_comfortLily_b' }],
  },
  C_comfortLily_b: {
    speaker: 'Narrator',
    text: 'As you touch her, the angry reflection shrieks and shatters like glass. The world rights itself.',
    background: BG.mirror_realm,
    sfx: SFX.mirror_shatter,
    effects: { stats: { morality: 5 } },
    choices: [{ text: "It's over...", next: 'C_escape' }],
  },
  C_escape: {
    speaker: 'Lily',
    background: BG.storage_closet,
    text: "'Thank you,' whispers the small, peaceful spirit of Lily, before fading away. You find yourself standing in a dusty, unused storage closet. She has freed you. One door leads back to the Children's Ward, and a smaller one is marked 'Maintenance Access'.",
    effects: { flags: { set: 'C_completed' } },
    choices: [
      { text: 'Go to Maintenance Access.', next: 'A_maintCorridor_Entry' },
      { text: "Return to the Children's Ward.", next: 'C_followLaughter' },
      {
        text: 'This wing is a dead end. Move on.',
        next: { chapter: 'chapter2', key: 'start' },
      },
    ],
  },
};
